### ISSUE TITLE
Don't try to parse org markup in #+BEGIN_HTML

### ISSUE THREAD

**Issue by ggreif** [melioratus/org-mode#9] opened 2018-03-19 10:26 UTC
Consider following org markup:
```
#+BEGIN_HTML
<svg viewBox="100 -10 500 600" width="700" height="600">
   <use xlink:href="RegAddress.svg#pattern"></use>
</svg>
#+END_HTML
```
The parser gets confused by the `/use ... </` part. I think this shouldn't be parsed as org markup, but (optionally) as HTML syntax.

**Comment by melioratus** [comment] 2018-05-13 18:44
@ggreif 

Added grammar support for HTML Block and EXPORT HTML block syntax.

Please upgrade to v.0.3.16.

I'm going to close this issue. However, if you discover that the issue is not resolved after upgrading to 0.3.16 or above, then please reply with a syntax example and I will reopen the ticket.

Thanks for your help!

Brian K. ~ @melioratus

**Closed by melioratus** 2018-05-13 18:44 UTC
Labels: bug
